### PR TITLE
Document OnDemand 2.0 upgrade and installation

### PR DESCRIPTION
**Pull request by treydock**
Set base branch to branch used for #491

### CODE REVIEW

**Comment by treydock** [comment]
Fixes #459

**Comment by johrstrom** [comment]
What about #490 and enabling powertools?

**Comment by treydock** [comment]
I added a commit just now to ensure that CentOS / RHEL repos are enabled. The repo name `powertools` is specific to CentOS so have to document what to enable for RHEL too.

**Review by johrstrom — APPROVED** [review]
Thanks! LGTM.

**Pull request merged**
