### PR TITLE
RPM will move /var/lib/nginx/config to /var/lib/nginx/config.rpmsave

### PR DESCRIPTION
**Pull request by treydock**

### CODE REVIEW

**Comment by treydock** [comment]
Don't merge this yet, I am going to have to make changes to RPM and will make the documentation changes here.

**Comment by treydock** [comment]
Added commit to account for recent RPM changes, this is good now.

**Comment by ericfranz** [comment]
Okay I merged the other so we now always source the default profile first, so this can be reworded.

**Comment by treydock** [comment]
Added commit to describe the change in behavior.  I got writer's block so am open to suggestions on how to better word the warning.

**Pull request merged**
