### PR TITLE
Document NodeJS 14 upgrade

### LINKED ISSUE #729: [release_2.0] Upgrade to NodeJS 14
Create documentation for https://github.com/OSC/ondemand/pull/2316

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1203119095508423) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by treydock**
Fixes #729

**Modify this link to include the branch name, and possibly the page this PR modifies**:

https://osc.github.io/ood-documentation-test/nodejs14/

**Add your description here**

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203119224963737) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by treydock** [comment]
I had to tweak the Rake task to build locally to match what's in Github actions.

**Comment by johrstrom** [comment]
This is fine, but it'll have to keep until we actually cut the release.

**Comment by treydock** [comment]
@johrstrom Should this get merged now that 2.0.29 exists?

**Comment by johrstrom** [comment]
IDK - it's not on latest yet, I'd bet we'll confuse folks given they can't actually get it yet.

**Pull request merged**
