### PR TITLE
Document the display option of an attribute.

### PR DESCRIPTION
**Pull request by james-s-willis**
**Modify this link to include the branch name, and possibly the page this PR modifies**:

https://osc.github.io/ood-documentation-test/develop/enable-desktops/modify-form-attributes.html

Documents how to show a form attribute in the session card. Related to https://github.com/OSC/ondemand/issues/2342.

I think this is the correct page for this?

### CODE REVIEW

**Comment by johrstrom** [comment]
Seems like it should be here: https://osc.github.io/ood-documentation-test/latest/how-tos/app-development/interactive/form.html#customizing-attributes

and maybe a new section included under `interactive.rst` to maybe highlight the feature to be more discoverable?

**Comment by james-s-willis** [comment]
Ah my mistake, sorry. I completely missed that it was already in the documentation, it's pretty clear. I had only found it in that 2342 issue.

**Comment by johrstrom** [comment]
🤦‍♂️ lol I didn't notice that it was there, I just pulled the link without reading or remembering that it was.

Well, seems like we still have a discoverability issue. Maybe a new section included under `interactive.rst` can have a small snippet pointing back to this? That way it's on the Table of Contents when you open interactive app development.  Maybe if it's there in the ToC folks will see it?

**Comment by james-s-willis** [comment]
I've moved the section under `interactive.rst` and added a link back to the `display` option. Is that what you had in mind?

**Comment by johrstrom** [comment]
> Is that what you had in mind?

Not really, but I can merge this and/or fix it up and merge. I'm just a bit busy to do it at this moment.

I guess I'm starting to realize we need  some sort of `source/how-tos/app-development/interactive/advanced.rst` where we can outline special use cases like this that aren't super discoverable. 

I'm thinking it's sort of `here's everything` (what we have now) and another entry in the main ToC that's 
along the lines of `advanced settings` or just next level stuff you'd want to do (advanced is the best word I have for this off the top, but not quite the best I think).

image\

Seems like some of those other pages could even collapse into it like the `Adding additional information to session cards`.

**Comment by johrstrom** [comment]
Thanks again for this correction. I've added a new section in the ToC to try to capture advanced features like this in case folks can't find it buried elsewhere.

**Pull request merged**
